export const ListShowInfo = [
  {
    id: 1,
    autor: 'Jones Souza',
    like: '1.7M',
    percentage: '72%',
    description: 'Sexta-feira é dia de Maldade feat programador Java',
  },
  {
    id: 2,
    autor: 'Chaves Borges',
    like: '1.2M',
    percentage: '52%',
    description:
      'Undefined is not a funcion f*dendo dev em reunião de apresentação',
  },
  {
    id: 3,
    autor: 'Saulo Bass',
    like: '1.4M',
    percentage: '45%',
    description: 'Programador Deno manda recado para NodeJS',
  },
  {
    id: 4,
    autor: 'Jones Souza',
    like: '1.7M',
    percentage: '72%',
    description: 'Trio fazendo deploy Sexta-feira à noite',
  },
  {
    id: 5,
    autor: 'Chaves Borges',
    like: '1.2M',
    percentage: '52%',
    description: 'Fazendo testes de penetração em bash',
  },
  {
    id: 6,
    autor: 'Saulo Bass',
    like: '1.4M',
    percentage: '45%',
    description: 'Usando Regex para f*der a entrega na sexta-feira',
  },
  {
    id: 7,
    autor: 'Jones Souza',
    like: '1.7M',
    percentage: '72%',
    description: 'Só faz testes quem não tem coragem',
  },
  {
    id: 8,
    autor: 'Chaves Borges',
    like: '1.2M',
    percentage: '52%',
    description: 'Apresentação funcionalidades do ReactJS',
  },
  {
    id: 9,
    autor: 'Saulo Bass',
    like: '1.4M',
    percentage: '45%',
    description: 'CSS é para os fortes',
  },
  {
    id: 10,
    autor: 'Jones Souza',
    like: '1.7M',
    percentage: '72%',
    description: 'Deitando dev JavaScript na porrada',
  },
  {
    id: 11,
    autor: 'Chaves Borges',
    like: '1.2M',
    percentage: '52%',
    description: 'Conceitos do TailwindCSS e Técnicas',
  },
  {
    id: 12,
    autor: 'Saulo Bass',
    like: '1.4M',
    percentage: '45%',
    description: 'Programa em Javascript é fantastico, mehor linguagem',
  },
]
